kind: pipeline
name: lint-typecheck-build
type: docker

trigger:
  event:
    - pull_request
  branch:
    - master

steps:
  - name: install
    image: node:16.9.1
    commands:
      - cd frontend
      - yarn install

  - name: lint
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd frontend
      - yarn lint

  - name: build-and-typescript-check
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd frontend
      - yarn build

---
kind: pipeline
name: build-publish-deploy
type: docker

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: delete
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SERVER_HOST
      port:
        from_secret: SERVER_PORT
      username:
        from_secret: SERVER_USER
      password:
        from_secret: SERVER_PASSWORD
      script:
        - docker-compose down
        - rm -R /home/web/website-fallback

  - name: deploy
    depends_on: [ delete ]
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SERVER_HOST
      port:
        from_secret: SERVER_PORT
      username:
        from_secret: SERVER_USER
      password:
        from_secret: SERVER_PASSWORD
      target: /home/web/website-fallback
      source: ./*
      strip_components: 0

  - name: start
    depends_on: [deploy]
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SERVER_HOST
      port:
        from_secret: SERVER_PORT
      username:
        from_secret: SERVER_USER
      password:
        from_secret: SERVER_PASSWORD
      script:
        - cd /home/web/website-fallback
        - docker-compose up -d --build
