version: "3"

services:
  client:
    stdin_open: true
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website-fallback.rule=Host(`woolgens.net`)"
      - "traefik.http.routers.website-fallback.tls=true"
      - "traefik.http.services.website-fallback.loadbalancer.server.port=3000"
      - "traefik.http.routers.website-fallback.priority=5"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true
